version: '3'

services:
  backend:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/course
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - ALLOWED_ORIGINS=https://185.189.167.175,https://185.189.167.175:8443
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    environment:
      - REACT_APP_BACKEND_URL=https://185.189.167.175:8443
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - app-network

  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
