version: '3'

services:
  backend:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/course
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    environment:
      - REACT_APP_BACKEND_URL=http://185.189.167.175
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - app-network

  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
